version: 2

updates:

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      lib-elixir:
        patterns:
          - "*"
          
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    groups:
      lib-javascript:
        patterns:
          - "*"

  - package-ecosystem: "mix"
    directory: "/test/features"
    schedule:
      interval: "weekly"
    groups:
      feature-tests:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"